# backend/autonomous/nmli_validator.py

import logging
from typing import Dict, Any, Optional

logger = logging.getLogger(__name__)

class AutonomousNMLIValidator:
    """
    Validates the structural integrity of NMLI proposals generated by the Autonomous Layer.
    Bypasses the NLP/SCSV explicit validator completely.
    Only checks schema requirements, NEVER executes or calculates Risk.
    """
    
    # Minimum required fields per tool (based on Alpaca schemas)
    REQUIRED_ARGS = {
        "place_stock_order": ["symbol", "side"],
        "place_option_order": ["qty"],
        "place_crypto_order": ["symbol", "side"]
    }

    @classmethod
    def validate(cls, raw_proposal: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        """
        Validates the raw proposal dictionary. 
        Returns the validated structured NMLI dict or None if invalid.
        """
        try:
            tool_name = raw_proposal.get("tool_name")
            arguments = raw_proposal.get("arguments", {})
            
            if not tool_name or not isinstance(arguments, dict):
                logger.error("NMLI Validation failed: Missing tool_name or arguments.")
                return None
                
            # 1. Check required arguments structurally
            required = cls.REQUIRED_ARGS.get(tool_name, [])
            for req in required:
                if req not in arguments:
                    logger.error(f"NMLI Validation failed: Missing required argument '{req}' for tool '{tool_name}'.")
                    return None

            # 2. Multi-leg structural check for options
            if tool_name == "place_option_order" and "legs" in arguments:
                legs = arguments["legs"]
                if not isinstance(legs, list) or not (1 <= len(legs) <= 4):
                    logger.error("NMLI Validation failed: Legs must be a list of 1 to 4 items.")
                    return None
                for leg in legs:
                    if "symbol" not in leg or "ratio_qty" not in leg:
                        logger.error("NMLI Validation failed: Each leg must contain 'symbol' and 'ratio_qty'.")
                        return None

            # 3. Inject strict source metadata (Guarantees origin tracing)
            metadata = raw_proposal.get("metadata", {})
            metadata["source"] = "AUTONOMOUS_TRIGGER"
            
            return {
                "tool_name": tool_name,
                "arguments": arguments,
                "metadata": metadata
            }

        except Exception as e:
            logger.error(f"NMLI Validation exception safely caught: {e}")
            return None